# Generated by Django 2.1.4 on 2020-05-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190208_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=True, verbose_name='first connection'),
        ),
    ]
