# Generated by Django 2.1.4 on 2020-05-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_onboarding'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_invite', 'Can invite users'),)},
        ),
    ]
