# Generated by Django 2.1.4 on 2020-08-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200520_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding',
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_images',
            field=models.BooleanField(default=False, verbose_name='first connection'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_models',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_trans',
            field=models.BooleanField(default=False),
        ),
    ]
