# Generated by Django 2.1.4 on 2020-08-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200818_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding_edit',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_images',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_models',
        ),
        migrations.RemoveField(
            model_name='user',
            name='onboarding_trans',
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=True, verbose_name='first connection'),
        ),
    ]
