# Generated by Django 2.1.4 on 2020-12-03 11:21

from django.db import migrations


def forward(apps, se):
    Group = apps.get_model('auth', 'Group')
    GroupOwner = apps.get_model('users', 'GroupOwner')

    groups_without_owner = Group.objects.filter(groupowner__isnull=True)
    for group in groups_without_owner:
        GroupOwner.objects.create(group=group, owner=group.user_set.first())


def backward(apps, se):
    # no need to do anything
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_groupowner'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
