# Generated by Django 2.1.4 on 2021-01-06 13:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_create_group_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='onboarding',
            field=models.BooleanField(default=True, verbose_name='Show onboarding'),
        ),
    ]
