# Generated by Django 2.2.19 on 2021-03-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210106_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact message', 'verbose_name_plural': 'Contact messages'},
        ),
    ]
