# Generated by Django 2.2.23 on 2021-10-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_update_domain_n_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quota_cpu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quota_disk_storage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='quota_gpu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
