# Generated by Django 2.2.23 on 2021-11-09 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20211006_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotaEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reached_disk_storage', models.PositiveIntegerField(blank=True, null=True)),
                ('reached_cpu', models.PositiveIntegerField(blank=True, null=True)),
                ('reached_gpu', models.PositiveIntegerField(blank=True, null=True)),
                ('sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quota_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
