# Generated by Django 4.0.10 on 2023-02-22 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20220608_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='onboarding',
        ),
    ]
