# Generated by Django 4.0.10 on 2023-06-16 19:10

from django.db import migrations, models


def set_current_users_legacy_mode(apps, schema_editor):
    """Set all current users to use legacy mode to prevent unexpected interruptions.
    New user signups will still have legacy_mode default to False."""
    User = apps.get_model('users', 'User')
    User.objects.all().update(legacy_mode=True)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_user_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='legacy_mode',
            field=models.BooleanField(default=False, help_text='Use the legacy version of the user interface. If unchecked, features that have not yet been ported to the new interface may become unavailable. Likewise, if checked, newer features may become unavailable.'),
        ),
        migrations.RunPython(set_current_users_legacy_mode, reverse_code=migrations.RunPython.noop),
    ]
