# Generated by Django 4.2.30 on 2026-07-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_user_legacy_mode_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='download_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days downloads (exports, archives) are kept on the server before automatic cleanup. Set to 0 to disable auto-cleanup.'),
        ),
    ]
