# Generated by Django 4.2.29 on 2026-06-26 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_font_document_transcription_font_and_more'),
        ('users', '0023_alter_user_legacy_mode_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_transcription_font',
            field=models.ForeignKey(blank=True, help_text='Font used to render transcription content in the editor, unless overridden at the document or project level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.font', verbose_name='Preferred transcription font'),
        ),
    ]
