# Generated by Django 4.2.30 on 2026-09-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_user_download_retention_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='recipient_email',
            field=models.EmailField(max_length=254, verbose_name='Recipient email'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='recipient_first_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recipient first name'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='recipient_last_name',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Recipient last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='download_retention_days',
            field=models.PositiveIntegerField(default=30, help_text='How many days downloads (exports, archives) are kept on the server before automatic cleanup. Set to 0 to disable auto-cleanup.', verbose_name='Download retention days'),
        ),
        migrations.AlterField(
            model_name='user',
            name='legacy_mode',
            field=models.BooleanField(default=False, help_text='Use the legacy version of the user interface. If unchecked, features that have not yet been ported to the new interface may become unavailable. Likewise, if checked, newer features may become unavailable.', verbose_name='Legacy mode'),
        ),
    ]
