stages:
  - test
  - build
  - deploy

tests:
  stage: test
  image: registry.gitlab.com/scripta/escriptorium/base:0.10.1b

  services:
    - postgres:13-alpine
    - redis:alpine

  variables:
    # Databases settings
    REDIS_HOST: redis
    REDIS_PORT: 6379
    SQL_HOST: postgres
    POSTGRES_DB: escriptorium
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres

    # Pip cache
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

  cache:
    paths:
      - .cache/pip

  except:
    - schedules

  script:
    - python app/manage.py test -v 2 users api versioning imports core

build:
  stage: build
  image: node:12-alpine

  artifacts:
    paths:
      - front/dist
    expire_in: 2 weeks

  before_script:
    - cd front
    - npm ci

  script:
    - npm run production

.docker-build:
  stage: build
  image: docker:19.03.1
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_HOST: tcp://docker:2375/

docker-build-app:
  extends: .docker-build

  script:
    - ci/build.sh app

docker-build-exim:
  extends: .docker-build

  script:
    - ci/build.sh exim

docker-build-nginx:
  extends: .docker-build

  script:
    - ci/build.sh nginx

docker-build-base:
  extends: .docker-build

  # Run this only on base tags
  rules:
    - if: '$CI_COMMIT_TAG =~ /^base-.*/'
      when: on_success
    - when: never

  script:
    - ci/build-base.sh
