# Generated by Django 2.1.4 on 2019-04-03 12:32

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_on', models.DateTimeField(auto_now=True)),
                ('workflow_state', models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Started'), (2, 'Done'), (5, 'Error')])),
                ('parts', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('import_file', models.FileField(upload_to='import_src/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml'])])),
                ('processed', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
