# Generated by Django 2.1.4 on 2019-04-03 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190317_1550'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('imports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Document'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='import',
            name='error_message',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='import',
            name='started_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='import',
            name='started_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
