# Generated by Django 2.1.4 on 2019-04-09 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0002_auto_20190403_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='import',
            options={'ordering': ('-started_on',)},
        ),
        migrations.AddField(
            model_name='import',
            name='total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='import',
            name='import_file',
            field=models.FileField(upload_to='import_src/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'alto', 'abbyy'])]),
        ),
        migrations.AlterField(
            model_name='import',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Started'), (2, 'Done'), (5, 'Error')], default=0),
        ),
    ]
