# Generated by Django 2.1.4 on 2019-04-11 10:48

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_auto_20190409_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='total',
        ),
        migrations.AlterField(
            model_name='import',
            name='import_file',
            field=models.FileField(upload_to='import_src/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'alto', 'abbyy', 'json'])]),
        ),
        migrations.AlterField(
            model_name='import',
            name='parts',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
