# Generated by Django 2.1.4 on 2019-04-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0004_auto_20190411_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='task_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
