# Generated by Django 2.1.4 on 2019-05-07 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0005_import_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='import',
            name='name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='import',
            name='override',
            field=models.BooleanField(default=True),
        ),
    ]
