# Generated by Django 2.1.4 on 2019-10-14 09:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0006_auto_20190507_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='import',
            name='parts',
        ),
        migrations.AlterField(
            model_name='import',
            name='import_file',
            field=models.FileField(upload_to='import_src/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'alto', 'json'])]),
        ),
    ]
