# Generated by Django 2.1.4 on 2019-10-14 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0007_auto_20191014_0949'),
    ]

    operations = [
        migrations.RenameModel('Import', 'DocumentImport')
    ]
