# Generated by Django 2.1.4 on 2019-10-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0008_auto_20191014_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimport',
            name='total',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
