# Generated by Django 2.1.4 on 2019-10-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0009_documentimport_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimport',
            name='override',
            field=models.BooleanField(default=False),
        ),
    ]
