# Generated by Django 3.1.14 on 2022-06-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0011_auto_20201009_1015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentimport',
            options={'ordering': ['-started_on']},
        ),
    ]
