# Generated by Django 4.0.5 on 2022-11-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0012_auto_20220608_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimport',
            name='with_mets',
            field=models.BooleanField(default=False),
        ),
    ]
