# Generated by Django 4.0.8 on 2022-12-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0013_documentimport_with_mets'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentimport',
            name='mets_base_uri',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
