# Generated by Django 4.0.10 on 2023-03-14 09:33

import django.core.validators
from django.db import migrations, models

import imports.models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0014_documentimport_mets_base_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentimport',
            name='import_file',
            field=models.FileField(upload_to=imports.models.document_import_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xml', 'alto', 'json'])]),
        ),
    ]
