// Utility to store the initial state for each form, so that forms can easily be cleared by key/name

export default {
    addComponent: {
        name: "",
        values: "",
    },
    align: {
        addHyphens: false,
        beamSize: "",
        gap: 600,
        layerName: "",
        maxOffset: "",
        merge: false,
        ngram: 25,
        overwriteWarningVisible: false,
        regionTypes: [],
        showAdvanced: false,
        threshold: 0.8,
        textualWitness: "",
        textualWitnessFile: null,
        textualWitnessType: "select",
        tooltipShown: {
            beamSize: false,
            gap: false,
            maxOffset: false,
            ngram: false,
            threshold: false,
        },
        transcription: "",
        fullDoc: false,
    },
    editDocument: {
        linePosition: "",
        mainScript: "",
        metadata: [],
        name: "",
        readDirection: "",
        tags: [],
        tagName: "",
        transcriptionFont: "",
    },
    editProject: {
        guidelines: "",
        name: "",
        tags: [],
        tagName: "",
        transcriptionFont: "",
    },
    elementDetails: {
        comments: "",
        metadata: [],
        name: "",
        typology: "",
    },
    export: {
        fileFormat: "",
        includeAll: false,
        includeImages: false,
        includeCharacters: false,
        includeMetadata: false,
        includeModels: false,
        includeAnnotations: false,
        allTranscriptions: false,
        regionTypes: [],
        transcription: "",
    },
    import: {
        iiifUri: "",
        imagesComplete: false,
        imagesLoading: false,
        layerName: "",
        metsType: "url",
        metsUri: "",
        mode: "images",
        overwrite: false,
        uploadFile: "",
    },
    downloadArchive: {
        archiveFormat: "zip",
        includeImages: true,
    },
    moveImages: {
        index: "",
        location: "before",
    },
    ontology: {
        image: [],
        lines: [],
        parts: [],
        regions: [],
        text: [],
    },
    segment: {
        model: "",
        overwrite: false,
        include: [],
        textDirection: "",
    },
    share: {
        group: "",
        user: "",
    },
    train: {
        model: "",
        modelName: "",
        override: false,
        transcription: "",
    },
    transcribe: {
        model: "",
        layerName: "",
    },
    transcriptionManagement: {
        transcriptions: [],
    },
};
