# Generated by Django 2.2.23 on 2021-09-20 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_taskreport_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='cpu_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
