# Generated by Django 2.2.23 on 2021-09-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_taskreport_cpu_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='gpu_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
