# Generated by Django 2.2.23 on 2021-11-25 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20211008_1250'),
        ('reporting', '0004_taskreport_gpu_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.Document'),
        ),
    ]
