# Generated by Django 4.0.5 on 2022-10-17 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_document_valid_part_types_documentpartmetadata'),
        ('reporting', '0006_taskreport_part_and_canceled_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskreport',
            name='ocr_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='core.ocrmodel'),
        ),
    ]
