# Generated by Django 4.2.28 on 2026-03-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_virtualcollection_virtualcollectionitem_and_more"),
        ("reporting", "0009_alter_taskgroup_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskgroup",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.virtualcollection",
            ),
        ),
        migrations.AddField(
            model_name="taskreport",
            name="collection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="core.virtualcollection",
            ),
        ),
        migrations.AlterField(
            model_name="taskgroup",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.document",
            ),
        ),
    ]
