# Generated by Django 4.2.30 on 2026-08-15 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import reporting.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporting', '0011_taskreport_task_id_workflow_state_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(db_index=True, default=reporting.models._new_download_fingerprint, max_length=32, unique=True)),
                ('label', models.CharField(max_length=256)),
                ('file_path', models.CharField(max_length=1024)),
                ('file_size', models.BigIntegerField(default=0)),
                ('mime_type', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('accessed_at', models.DateTimeField(blank=True, null=True)),
                ('accessed_count', models.PositiveIntegerField(default=0)),
                ('task_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='reporting.taskreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
