export const scripts = [
    "Adlam",
    "Afaka",
    "Ahom, Tai Ahom",
    "Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)",
    "Arabic",
    "Arabic (Nastaliq variant)",
    "Armenian",
    "Avestan",
    "Balinese",
    "Bamum",
    "Bassa Vah",
    "Batak",
    "Bengali (Bangla)",
    "Bhaiksuki",
    "Blissymbols",
    "Book Pahlavi",
    "Bopomofo",
    "Brahmi",
    "Braille",
    "Buginese",
    "Buhid",
    "Carian",
    "Caucasian Albanian",
    "Chakma",
    "Cham",
    "Cherokee",
    "Cirth",
    "Code for inherited script",
    "Code for uncoded script",
    "Code for undetermined script",
    "Code for unwritten documents",
    "Coptic",
    "Cuneiform, Sumero-Akkadian",
    "Cypriot syllabary",
    "Cypro-Minoan",
    "Cyrillic",
    "Cyrillic (Old Church Slavonic variant)",
    "Deseret (Mormon)",
    "Devanagari (Nagari)",
    "Dogra",
    "Duployan shorthand, Duployan stenography",
    "Egyptian demotic",
    "Egyptian hieratic",
    "Egyptian hieroglyphs",
    "Elbasan",
    "Elymaic",
    "Ethiopic (Geʻez)",
    "Georgian (Mkhedruli and Mtavruli)",
    "Glagolitic",
    "Gothic",
    "Grantha",
    "Greek",
    "Gujarati",
    "Gunjala Gondi",
    "Gurmukhi",
    "Han (Hanzi, Kanji, Hanja)",
    "Han (Simplified variant)",
    "Han (Traditional variant)",
    "Han with Bopomofo (alias for Han + Bopomofo)",
    "Hangul (Hangŭl, Hangeul)",
    "Hanifi Rohingya",
    "Hanunoo (Hanunóo)",
    "Hatran",
    "Hebrew",
    "Hiragana",
    "Imperial Aramaic",
    "Indus (Harappan)",
    "Inscriptional Pahlavi",
    "Inscriptional Parthian",
    "Jamo (alias for Jamo subset of Hangul)",
    "Japanese (alias for Han + Hiragana + Katakana)",
    "Japanese syllabaries (alias for Hiragana + Katakana)",
    "Javanese",
    "Jurchen",
    "Kaithi",
    "Kannada",
    "Katakana",
    "Kayah Li",
    "Kharoshthi",
    "Khitan large script",
    "Khitan small script",
    "Khmer",
    "Khojki",
    "Khudawadi, Sindhi",
    "Khutsuri (Asomtavruli and Nuskhuri)",
    "Klingon (KLI pIqaD)",
    "Korean (alias for Hangul + Han)",
    "Kpelle",
    "Lao",
    "Latin",
    "Latin (Fraktur variant)",
    "Latin (Gaelic variant)",
    "Leke",
    "Lepcha (Róng)",
    "Limbu",
    "Linear A",
    "Linear B",
    "Lisu (Fraser)",
    "Loma",
    "Lycian",
    "Lydian",
    "Mahajani",
    "Makasar",
    "Malayalam",
    "Mandaic, Mandaean",
    "Manichaean",
    "Marchen",
    "Masaram Gondi",
    "Mathematical notation",
    "Mayan hieroglyphs",
    "Medefaidrin (Oberi Okaime, Oberi Ɔkaimɛ)",
    "Meitei Mayek (Meithei, Meetei)",
    "Mende Kikakui",
    "Meroitic Cursive",
    "Meroitic Hieroglyphs",
    "Miao (Pollard)",
    "Modi, Moḍī",
    "Mongolian",
    "Moon (Moon code, Moon script, Moon type)",
    "Mro, Mru",
    "Multani",
    "Myanmar (Burmese)",
    "Nabataean",
    "Nandinagari",
    "Naxi Dongba (na²¹ɕi³³ to³³ba²¹, Nakhi Tomba)",
    "Naxi Geba (na²¹ɕi³³ gʌ²¹ba²¹, 'Na-'Khi ²Ggŏ-¹baw, Nakhi Geba)",
    "New Tai Lue",
    "Newa, Newar, Newari, Nepāla lipi",
    "Nüshu",
    "Nyiakeng Puachue Hmong",
    "N’Ko",
    "Ogham",
    "Ol Chiki (Ol Cemet’, Ol, Santali)",
    "Old Hungarian (Hungarian Runic)",
    "Old Italic (Etruscan, Oscan, etc.)",
    "Old North Arabian (Ancient North Arabian)",
    "Old Permic",
    "Old Persian",
    "Old Sogdian",
    "Old South Arabian",
    "Old Turkic, Orkhon Runic",
    "Oriya (Odia)",
    "Osage",
    "Osmanya",
    "Pahawh Hmong",
    "Palmyrene",
    "Pau Cin Hau",
    "Phags-pa",
    "Phoenician",
    "Psalter Pahlavi",
    "Rejang (Redjang, Kaganga)",
    "Reserved for private use (end)",
    "Reserved for private use (start)",
    "Rongorongo",
    "Runic",
    "Samaritan",
    "Sarati",
    "Saurashtra",
    "Sharada, Śāradā",
    "Shavian (Shaw)",
    "Shuishu",
    "Siddham, Siddhaṃ, Siddhamātṛkā",
    "SignWriting",
    "Sinhala",
    "Sogdian",
    "Sora Sompeng",
    "Soyombo",
    "Sundanese",
    "Syloti Nagri",
    "Symbols",
    "Symbols (Emoji variant)",
    "Syriac",
    "Syriac (Eastern variant)",
    "Syriac (Estrangelo variant)",
    "Syriac (Western variant)",
    "Tagalog (Baybayin, Alibata)",
    "Tagbanwa",
    "Tai Le",
    "Tai Tham (Lanna)",
    "Tai Viet",
    "Takri, Ṭākrī, Ṭāṅkrī",
    "Tamil",
    "Tangut",
    "Telugu",
    "Tengwar",
    "Thaana",
    "Thai",
    "Tibetan",
    "Tifinagh (Berber)",
    "Tirhuta",
    "Ugaritic",
    "Unified Canadian Aboriginal Syllabics",
    "Vai",
    "Visible Speech",
    "Wancho",
    "Warang Citi (Varang Kshiti)",
    "Woleai",
    "Yi",
    "Zanabazar Square (Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script)"
];
