export const scripts = [
    {
        id: 1,
        name: "Adlam",
        name_fr: "adlam",
        iso_code: "Adlm",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 2,
        name: "Afaka",
        name_fr: "afaka",
        iso_code: "Afak",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 4,
        name: "Ahom, Tai Ahom",
        name_fr: "âhom",
        iso_code: "Ahom",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 62,
        name: "Anatolian Hieroglyphs (Luwian Hieroglyphs, Hittite Hieroglyphs)",
        name_fr:
            "hiéroglyphes anatoliens (hiéroglyphes louvites, hiéroglyphes hittites)",
        iso_code: "Hluw",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 5,
        name: "Arabic",
        name_fr: "arabe",
        iso_code: "Arab",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 6,
        name: "Arabic (Nastaliq variant)",
        name_fr: "arabe (variante nastalique)",
        iso_code: "Aran",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 8,
        name: "Armenian",
        name_fr: "arménien",
        iso_code: "Armn",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 9,
        name: "Avestan",
        name_fr: "avestique",
        iso_code: "Avst",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 10,
        name: "Balinese",
        name_fr: "balinais",
        iso_code: "Bali",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 11,
        name: "Bamum",
        name_fr: "bamoum",
        iso_code: "Bamu",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 12,
        name: "Bassa Vah",
        name_fr: "bassa",
        iso_code: "Bass",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 13,
        name: "Batak",
        name_fr: "batik",
        iso_code: "Batk",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 14,
        name: "Bengali (Bangla)",
        name_fr: "bengalî (bangla)",
        iso_code: "Beng",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 15,
        name: "Bhaiksuki",
        name_fr: "bhaïksukî",
        iso_code: "Bhks",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 16,
        name: "Blissymbols",
        name_fr: "symboles Bliss",
        iso_code: "Blis",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 136,
        name: "Book Pahlavi",
        name_fr: "pehlevi des livres",
        iso_code: "Phlv",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 17,
        name: "Bopomofo",
        name_fr: "bopomofo",
        iso_code: "Bopo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 18,
        name: "Brahmi",
        name_fr: "brahma",
        iso_code: "Brah",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 19,
        name: "Braille",
        name_fr: "braille",
        iso_code: "Brai",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 20,
        name: "Buginese",
        name_fr: "bouguis",
        iso_code: "Bugi",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 21,
        name: "Buhid",
        name_fr: "bouhide",
        iso_code: "Buhd",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 24,
        name: "Carian",
        name_fr: "carien",
        iso_code: "Cari",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 3,
        name: "Caucasian Albanian",
        name_fr: "aghbanien",
        iso_code: "Aghb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 22,
        name: "Chakma",
        name_fr: "chakma",
        iso_code: "Cakm",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 25,
        name: "Cham",
        name_fr: "cham (čam, tcham)",
        iso_code: "Cham",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 26,
        name: "Cherokee",
        name_fr: "tchérokî",
        iso_code: "Cher",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 27,
        name: "Cirth",
        name_fr: "cirth",
        iso_code: "Cirt",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 193,
        name: "Code for inherited script",
        name_fr: "codet pour écriture héritée",
        iso_code: "Zinh",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 199,
        name: "Code for uncoded script",
        name_fr: "codet pour écriture non codée",
        iso_code: "Zzzz",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 198,
        name: "Code for undetermined script",
        name_fr: "codet pour écriture indéterminée",
        iso_code: "Zyyy",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 197,
        name: "Code for unwritten documents",
        name_fr: "codet pour les documents non écrits",
        iso_code: "Zxxx",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 28,
        name: "Coptic",
        name_fr: "copte",
        iso_code: "Copt",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 190,
        name: "Cuneiform, Sumero-Akkadian",
        name_fr: "cunéiforme suméro-akkadien",
        iso_code: "Xsux",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 30,
        name: "Cypriot syllabary",
        name_fr: "syllabaire chypriote",
        iso_code: "Cprt",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 29,
        name: "Cypro-Minoan",
        name_fr: "syllabaire chypro-minoen",
        iso_code: "Cpmn",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 31,
        name: "Cyrillic",
        name_fr: "cyrillique",
        iso_code: "Cyrl",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 32,
        name: "Cyrillic (Old Church Slavonic variant)",
        name_fr: "cyrillique (variante slavonne)",
        iso_code: "Cyrs",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 35,
        name: "Deseret (Mormon)",
        name_fr: "déseret (mormon)",
        iso_code: "Dsrt",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 33,
        name: "Devanagari (Nagari)",
        name_fr: "dévanâgarî",
        iso_code: "Deva",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 34,
        name: "Dogra",
        name_fr: "dogra",
        iso_code: "Dogr",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 36,
        name: "Duployan shorthand, Duployan stenography",
        name_fr: "sténographie Duployé",
        iso_code: "Dupl",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 37,
        name: "Egyptian demotic",
        name_fr: "démotique égyptien",
        iso_code: "Egyd",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 38,
        name: "Egyptian hieratic",
        name_fr: "hiératique égyptien",
        iso_code: "Egyh",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 39,
        name: "Egyptian hieroglyphs",
        name_fr: "hiéroglyphes égyptiens",
        iso_code: "Egyp",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 40,
        name: "Elbasan",
        name_fr: "elbasan",
        iso_code: "Elba",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 41,
        name: "Elymaic",
        name_fr: "élymaïque",
        iso_code: "Elym",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 42,
        name: "Ethiopic (Geʻez)",
        name_fr: "éthiopien (geʻez, guèze)",
        iso_code: "Ethi",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 44,
        name: "Georgian (Mkhedruli and Mtavruli)",
        name_fr: "géorgien (mkhédrouli et mtavrouli)",
        iso_code: "Geor",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 45,
        name: "Glagolitic",
        name_fr: "glagolitique",
        iso_code: "Glag",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 48,
        name: "Gothic",
        name_fr: "gotique",
        iso_code: "Goth",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 49,
        name: "Grantha",
        name_fr: "grantha",
        iso_code: "Gran",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 50,
        name: "Greek",
        name_fr: "grec",
        iso_code: "Grek",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 51,
        name: "Gujarati",
        name_fr: "goudjarâtî (gujrâtî)",
        iso_code: "Gujr",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 46,
        name: "Gunjala Gondi",
        name_fr: "gunjala gondî",
        iso_code: "Gong",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 52,
        name: "Gurmukhi",
        name_fr: "gourmoukhî",
        iso_code: "Guru",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 55,
        name: "Han (Hanzi, Kanji, Hanja)",
        name_fr: "idéogrammes han (sinogrammes)",
        iso_code: "Hani",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 57,
        name: "Han (Simplified variant)",
        name_fr: "idéogrammes han (variante simplifiée)",
        iso_code: "Hans",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 58,
        name: "Han (Traditional variant)",
        name_fr: "idéogrammes han (variante traditionnelle)",
        iso_code: "Hant",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 53,
        name: "Han with Bopomofo (alias for Han + Bopomofo)",
        name_fr: "han avec bopomofo (alias pour han + bopomofo)",
        iso_code: "Hanb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 54,
        name: "Hangul (Hangŭl, Hangeul)",
        name_fr: "hangûl (hangŭl, hangeul)",
        iso_code: "Hang",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 144,
        name: "Hanifi Rohingya",
        name_fr: "hanifi rohingya",
        iso_code: "Rohg",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 56,
        name: "Hanunoo (Hanunóo)",
        name_fr: "hanounóo",
        iso_code: "Hano",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 59,
        name: "Hatran",
        name_fr: "hatrénien",
        iso_code: "Hatr",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 60,
        name: "Hebrew",
        name_fr: "hébreu",
        iso_code: "Hebr",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 61,
        name: "Hiragana",
        name_fr: "hiragana",
        iso_code: "Hira",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 7,
        name: "Imperial Aramaic",
        name_fr: "araméen impérial",
        iso_code: "Armi",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 67,
        name: "Indus (Harappan)",
        name_fr: "indus",
        iso_code: "Inds",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 134,
        name: "Inscriptional Pahlavi",
        name_fr: "pehlevi des inscriptions",
        iso_code: "Phli",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 140,
        name: "Inscriptional Parthian",
        name_fr: "parthe des inscriptions",
        iso_code: "Prti",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 69,
        name: "Jamo (alias for Jamo subset of Hangul)",
        name_fr: "jamo (alias pour le sous-ensemble jamo du hangûl)",
        iso_code: "Jamo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 71,
        name: "Japanese (alias for Han + Hiragana + Katakana)",
        name_fr: "japonais (alias pour han + hiragana + katakana)",
        iso_code: "Jpan",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 65,
        name: "Japanese syllabaries (alias for Hiragana + Katakana)",
        name_fr: "syllabaires japonais (alias pour hiragana + katakana)",
        iso_code: "Hrkt",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 70,
        name: "Javanese",
        name_fr: "javanais",
        iso_code: "Java",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 72,
        name: "Jurchen",
        name_fr: "jurchen",
        iso_code: "Jurc",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 83,
        name: "Kaithi",
        name_fr: "kaithî",
        iso_code: "Kthi",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 80,
        name: "Kannada",
        name_fr: "kannara (canara)",
        iso_code: "Knda",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 74,
        name: "Katakana",
        name_fr: "katakana",
        iso_code: "Kana",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 73,
        name: "Kayah Li",
        name_fr: "kayah li",
        iso_code: "Kali",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 75,
        name: "Kharoshthi",
        name_fr: "kharochthî",
        iso_code: "Khar",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 78,
        name: "Khitan large script",
        name_fr: "grande écriture khitan",
        iso_code: "Kitl",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 79,
        name: "Khitan small script",
        name_fr: "petite écriture khitan",
        iso_code: "Kits",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 76,
        name: "Khmer",
        name_fr: "khmer",
        iso_code: "Khmr",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 77,
        name: "Khojki",
        name_fr: "khojkî",
        iso_code: "Khoj",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 156,
        name: "Khudawadi, Sindhi",
        name_fr: "khoudawadî, sindhî",
        iso_code: "Sind",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 43,
        name: "Khutsuri (Asomtavruli and Nuskhuri)",
        name_fr: "khoutsouri (assomtavrouli et nouskhouri)",
        iso_code: "Geok",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 139,
        name: "Klingon (KLI pIqaD)",
        name_fr: "klingon (pIqaD du KLI)",
        iso_code: "Piqd",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 81,
        name: "Korean (alias for Hangul + Han)",
        name_fr: "coréen (alias pour hangûl + han)",
        iso_code: "Kore",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 82,
        name: "Kpelle",
        name_fr: "kpèllé",
        iso_code: "Kpel",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 85,
        name: "Lao",
        name_fr: "laotien",
        iso_code: "Laoo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 88,
        name: "Latin",
        name_fr: "latin",
        iso_code: "Latn",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 86,
        name: "Latin (Fraktur variant)",
        name_fr: "latin (variante brisée)",
        iso_code: "Latf",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 87,
        name: "Latin (Gaelic variant)",
        name_fr: "latin (variante gaélique)",
        iso_code: "Latg",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 89,
        name: "Leke",
        name_fr: "léké",
        iso_code: "Leke",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 90,
        name: "Lepcha (Róng)",
        name_fr: "lepcha (róng)",
        iso_code: "Lepc",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 91,
        name: "Limbu",
        name_fr: "limbou",
        iso_code: "Limb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 92,
        name: "Linear A",
        name_fr: "linéaire A",
        iso_code: "Lina",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 93,
        name: "Linear B",
        name_fr: "linéaire B",
        iso_code: "Linb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 94,
        name: "Lisu (Fraser)",
        name_fr: "lisu (Fraser)",
        iso_code: "Lisu",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 95,
        name: "Loma",
        name_fr: "loma",
        iso_code: "Loma",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 96,
        name: "Lycian",
        name_fr: "lycien",
        iso_code: "Lyci",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 97,
        name: "Lydian",
        name_fr: "lydien",
        iso_code: "Lydi",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 98,
        name: "Mahajani",
        name_fr: "mahâjanî",
        iso_code: "Mahj",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 99,
        name: "Makasar",
        name_fr: "makassar",
        iso_code: "Maka",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 108,
        name: "Malayalam",
        name_fr: "malayâlam",
        iso_code: "Mlym",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 100,
        name: "Mandaic, Mandaean",
        name_fr: "mandéen",
        iso_code: "Mand",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 101,
        name: "Manichaean",
        name_fr: "manichéen",
        iso_code: "Mani",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 102,
        name: "Marchen",
        name_fr: "marchen",
        iso_code: "Marc",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 47,
        name: "Masaram Gondi",
        name_fr: "masaram gondî",
        iso_code: "Gonm",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 194,
        name: "Mathematical notation",
        name_fr: "notation mathématique",
        iso_code: "Zmth",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 103,
        name: "Mayan hieroglyphs",
        name_fr: "hiéroglyphes mayas",
        iso_code: "Maya",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 104,
        name: "Medefaidrin (Oberi Okaime, Oberi Ɔkaimɛ)",
        name_fr: "médéfaïdrine",
        iso_code: "Medf",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 113,
        name: "Meitei Mayek (Meithei, Meetei)",
        name_fr: "meitei mayek",
        iso_code: "Mtei",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 105,
        name: "Mende Kikakui",
        name_fr: "mendé kikakui",
        iso_code: "Mend",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 106,
        name: "Meroitic Cursive",
        name_fr: "cursif méroïtique",
        iso_code: "Merc",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 107,
        name: "Meroitic Hieroglyphs",
        name_fr: "hiéroglyphes méroïtiques",
        iso_code: "Mero",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 138,
        name: "Miao (Pollard)",
        name_fr: "miao (Pollard)",
        iso_code: "Plrd",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 109,
        name: "Modi, Moḍī",
        name_fr: "modî",
        iso_code: "Modi",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 110,
        name: "Mongolian",
        name_fr: "mongol",
        iso_code: "Mong",
        text_direction: "ttb",
        blank_char: " ",
    },
    {
        id: 111,
        name: "Moon (Moon code, Moon script, Moon type)",
        name_fr: "écriture Moon",
        iso_code: "Moon",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 112,
        name: "Mro, Mru",
        name_fr: "mro",
        iso_code: "Mroo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 114,
        name: "Multani",
        name_fr: "multanî",
        iso_code: "Mult",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 115,
        name: "Myanmar (Burmese)",
        name_fr: "birman",
        iso_code: "Mymr",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 118,
        name: "Nabataean",
        name_fr: "nabatéen",
        iso_code: "Nbat",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 116,
        name: "Nandinagari",
        name_fr: "nandinâgarî",
        iso_code: "Nand",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 120,
        name: "Naxi Dongba (na²¹ɕi³³ to³³ba²¹, Nakhi Tomba)",
        name_fr: "naxi dongba",
        iso_code: "Nkdb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 121,
        name: "Naxi Geba (na²¹ɕi³³ gʌ²¹ba²¹, 'Na-'Khi ²Ggŏ-¹baw, Nakhi Geba)",
        name_fr: "naxi geba, nakhi geba",
        iso_code: "Nkgb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 171,
        name: "New Tai Lue",
        name_fr: "nouveau taï-lue",
        iso_code: "Talu",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 119,
        name: "Newa, Newar, Newari, Nepāla lipi",
        name_fr: "néwa, néwar, néwari, nepāla lipi",
        iso_code: "Newa",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 123,
        name: "Nüshu",
        name_fr: "nüshu",
        iso_code: "Nshu",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 64,
        name: "Nyiakeng Puachue Hmong",
        name_fr: "nyiakeng puachue hmong",
        iso_code: "Hmnp",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 122,
        name: "N’Ko",
        name_fr: "n’ko",
        iso_code: "Nkoo",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 124,
        name: "Ogham",
        name_fr: "ogam",
        iso_code: "Ogam",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 125,
        name: "Ol Chiki (Ol Cemet’, Ol, Santali)",
        name_fr: "ol tchiki",
        iso_code: "Olck",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 66,
        name: "Old Hungarian (Hungarian Runic)",
        name_fr: "runes hongroises (ancien hongrois)",
        iso_code: "Hung",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 68,
        name: "Old Italic (Etruscan, Oscan, etc.)",
        name_fr: "ancien italique (étrusque, osque, etc.)",
        iso_code: "Ital",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 117,
        name: "Old North Arabian (Ancient North Arabian)",
        name_fr: "nord-arabique",
        iso_code: "Narb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 132,
        name: "Old Permic",
        name_fr: "ancien permien",
        iso_code: "Perm",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 189,
        name: "Old Persian",
        name_fr: "cunéiforme persépolitain",
        iso_code: "Xpeo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 159,
        name: "Old Sogdian",
        name_fr: "ancien sogdien",
        iso_code: "Sogo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 149,
        name: "Old South Arabian",
        name_fr: "sud-arabique, himyarite",
        iso_code: "Sarb",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 126,
        name: "Old Turkic, Orkhon Runic",
        name_fr: "orkhon",
        iso_code: "Orkh",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 127,
        name: "Oriya (Odia)",
        name_fr: "oriyâ (odia)",
        iso_code: "Orya",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 128,
        name: "Osage",
        name_fr: "osage",
        iso_code: "Osge",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 129,
        name: "Osmanya",
        name_fr: "osmanais",
        iso_code: "Osma",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 63,
        name: "Pahawh Hmong",
        name_fr: "pahawh hmong",
        iso_code: "Hmng",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 130,
        name: "Palmyrene",
        name_fr: "palmyrénien",
        iso_code: "Palm",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 131,
        name: "Pau Cin Hau",
        name_fr: "paou chin haou",
        iso_code: "Pauc",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 133,
        name: "Phags-pa",
        name_fr: "’phags pa",
        iso_code: "Phag",
        text_direction: "ttb",
        blank_char: " ",
    },
    {
        id: 137,
        name: "Phoenician",
        name_fr: "phénicien",
        iso_code: "Phnx",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 135,
        name: "Psalter Pahlavi",
        name_fr: "pehlevi des psautiers",
        iso_code: "Phlp",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 143,
        name: "Rejang (Redjang, Kaganga)",
        name_fr: "redjang (kaganga)",
        iso_code: "Rjng",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 142,
        name: "Reserved for private use (end)",
        name_fr: "réservé à l’usage privé (fin)",
        iso_code: "Qabx",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 141,
        name: "Reserved for private use (start)",
        name_fr: "réservé à l’usage privé (début)",
        iso_code: "Qaaa",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 145,
        name: "Rongorongo",
        name_fr: "rongorongo",
        iso_code: "Roro",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 146,
        name: "Runic",
        name_fr: "runique",
        iso_code: "Runr",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 147,
        name: "Samaritan",
        name_fr: "samaritain",
        iso_code: "Samr",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 148,
        name: "Sarati",
        name_fr: "sarati",
        iso_code: "Sara",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 150,
        name: "Saurashtra",
        name_fr: "saurachtra",
        iso_code: "Saur",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 153,
        name: "Sharada, Śāradā",
        name_fr: "charada, shard",
        iso_code: "Shrd",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 152,
        name: "Shavian (Shaw)",
        name_fr: "shavien (Shaw)",
        iso_code: "Shaw",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 154,
        name: "Shuishu",
        name_fr: "shuishu",
        iso_code: "Shui",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 155,
        name: "Siddham, Siddhaṃ, Siddhamātṛkā",
        name_fr: "siddham",
        iso_code: "Sidd",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 151,
        name: "SignWriting",
        name_fr: "SignÉcriture, SignWriting",
        iso_code: "Sgnw",
        text_direction: "ttb",
        blank_char: " ",
    },
    {
        id: 157,
        name: "Sinhala",
        name_fr: "singhalais",
        iso_code: "Sinh",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 158,
        name: "Sogdian",
        name_fr: "sogdien",
        iso_code: "Sogd",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 160,
        name: "Sora Sompeng",
        name_fr: "sora sompeng",
        iso_code: "Sora",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 161,
        name: "Soyombo",
        name_fr: "soyombo",
        iso_code: "Soyo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 162,
        name: "Sundanese",
        name_fr: "sundanais",
        iso_code: "Sund",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 163,
        name: "Syloti Nagri",
        name_fr: "sylotî nâgrî",
        iso_code: "Sylo",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 196,
        name: "Symbols",
        name_fr: "symboles",
        iso_code: "Zsym",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 195,
        name: "Symbols (Emoji variant)",
        name_fr: "symboles (variante émoji)",
        iso_code: "Zsye",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 164,
        name: "Syriac",
        name_fr: "syriaque",
        iso_code: "Syrc",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 167,
        name: "Syriac (Eastern variant)",
        name_fr: "syriaque (variante orientale)",
        iso_code: "Syrn",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 165,
        name: "Syriac (Estrangelo variant)",
        name_fr: "syriaque (variante estranghélo)",
        iso_code: "Syre",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 166,
        name: "Syriac (Western variant)",
        name_fr: "syriaque (variante occidentale)",
        iso_code: "Syrj",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 178,
        name: "Tagalog (Baybayin, Alibata)",
        name_fr: "tagal (baybayin, alibata)",
        iso_code: "Tglg",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 168,
        name: "Tagbanwa",
        name_fr: "tagbanoua",
        iso_code: "Tagb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 170,
        name: "Tai Le",
        name_fr: "taï-le",
        iso_code: "Tale",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 84,
        name: "Tai Tham (Lanna)",
        name_fr: "taï tham (lanna)",
        iso_code: "Lana",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 174,
        name: "Tai Viet",
        name_fr: "taï viêt",
        iso_code: "Tavt",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 169,
        name: "Takri, Ṭākrī, Ṭāṅkrī",
        name_fr: "tâkrî",
        iso_code: "Takr",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 172,
        name: "Tamil",
        name_fr: "tamoul",
        iso_code: "Taml",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 173,
        name: "Tangut",
        name_fr: "tangoute",
        iso_code: "Tang",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 175,
        name: "Telugu",
        name_fr: "télougou",
        iso_code: "Telu",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 176,
        name: "Tengwar",
        name_fr: "tengwar",
        iso_code: "Teng",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 179,
        name: "Thaana",
        name_fr: "thâna",
        iso_code: "Thaa",
        text_direction: "horizontal-rl",
        blank_char: " ",
    },
    {
        id: 180,
        name: "Thai",
        name_fr: "thaï",
        iso_code: "Thai",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 181,
        name: "Tibetan",
        name_fr: "tibétain",
        iso_code: "Tibt",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 177,
        name: "Tifinagh (Berber)",
        name_fr: "tifinagh (berbère)",
        iso_code: "Tfng",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 182,
        name: "Tirhuta",
        name_fr: "tirhouta",
        iso_code: "Tirh",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 183,
        name: "Ugaritic",
        name_fr: "ougaritique",
        iso_code: "Ugar",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 23,
        name: "Unified Canadian Aboriginal Syllabics",
        name_fr: "syllabaire autochtone canadien unifié",
        iso_code: "Cans",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 184,
        name: "Vai",
        name_fr: "vaï",
        iso_code: "Vaii",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 185,
        name: "Visible Speech",
        name_fr: "parole visible",
        iso_code: "Visp",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 187,
        name: "Wancho",
        name_fr: "wantcho",
        iso_code: "Wcho",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 186,
        name: "Warang Citi (Varang Kshiti)",
        name_fr: "warang citi",
        iso_code: "Wara",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 188,
        name: "Woleai",
        name_fr: "woléaï",
        iso_code: "Wole",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 191,
        name: "Yi",
        name_fr: "yi",
        iso_code: "Yiii",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
    {
        id: 192,
        name:
            "Zanabazar Square (Zanabazarin Dörböljin Useg, Xewtee Dörböljin Bicig, Horizontal Square Script)",
        name_fr: "zanabazar quadratique",
        iso_code: "Zanb",
        text_direction: "horizontal-lr",
        blank_char: " ",
    },
];
