# Generated by Django 2.1.3 on 2018-12-03 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterField(
            model_name='document',
            name='shared_with_groups',
            field=models.ManyToManyField(blank=True, related_name='shared_documents', to='auth.Group', verbose_name='Share with teams'),
        ),
        migrations.AlterField(
            model_name='document',
            name='shared_with_users',
            field=models.ManyToManyField(blank=True, related_name='shared_documents', to=settings.AUTH_USER_MODEL, verbose_name='Share with users'),
        ),
        migrations.AlterField(
            model_name='document',
            name='typology',
            field=models.ForeignKey(blank=True, limit_choices_to={'target': 1}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Typology'),
        ),
        migrations.AlterField(
            model_name='typology',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Document'), (2, 'Part (eg Page)'), (3, 'Block (eg Paragraph)')]),
        ),
    ]
