# Generated by Django 2.1.4 on 2019-01-21 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='document',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Document'),
        ),
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='auto_process',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='text_direction',
            field=models.CharField(choices=[('horizontal-lr', 'Horizontal l2r'), ('horizontal-rl', 'Horizontal r2l'), ('vertical-lr', 'Vertical l2r'), ('vertical-lr', 'Vertical r2l')], default='horizontal-lr', max_length=64),
        ),
    ]
