# Generated by Django 2.1.4 on 2018-12-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181203_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='access',
        ),
        migrations.AlterField(
            model_name='document',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (1, 'Shared'), (2, 'Published'), (3, 'Archived')], default=0),
        ),
    ]
