# Generated by Django 2.1.4 on 2019-01-28 09:40

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190121_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpart',
            name='bw_image',
            field=models.ImageField(blank=True, help_text='Binarized image needs to be the same size as original image.', null=True, upload_to=core.models.document_images_path),
        ),
    ]
