# Generated by Django 2.1.4 on 2018-12-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181204_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=512)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cidoc_id', models.CharField(max_length=8)),
            ],
        ),
        migrations.AddField(
            model_name='documentmetadata',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Metadata'),
        ),
        migrations.AddField(
            model_name='document',
            name='metadatas',
            field=models.ManyToManyField(blank=True, through='core.DocumentMetadata', to='core.Metadata'),
        ),
    ]
