# Generated by Django 2.1.4 on 2019-01-28 14:28

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190128_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='block',
            name='box',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='(0,0,1,1)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='block',
            name='document_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='core.DocumentPart'),
        ),
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='ocr_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_ocr', to='core.OcrModel', verbose_name='Model'),
        ),
    ]
