# Generated by Django 2.1.4 on 2018-12-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181206_0940'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentmetadata',
            unique_together=set(),
        ),
    ]
