# Generated by Django 2.1.4 on 2019-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190204_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrmodel',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
