# Generated by Django 2.1.4 on 2018-12-06 19:01

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181206_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpart',
            name='name',
            field=models.CharField(default='pouet', max_length=512),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documentpart',
            name='image',
            field=models.ImageField(upload_to=core.models.document_images_path),
        ),
    ]
