# Generated by Django 2.1.4 on 2019-03-04 14:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20190220_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetranscription',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='core.Line'),
        ),
        migrations.AlterField(
            model_name='ocrmodel',
            name='document',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Document'),
        ),
        migrations.AlterField(
            model_name='ocrmodel',
            name='file',
            field=models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['clstm', 'pronn'])]),
        ),
    ]
