# Generated by Django 2.1.4 on 2018-12-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20181206_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpart',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='core.Document'),
        ),
    ]
