# Generated by Django 2.1.4 on 2018-12-10 10:32

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20181206_2044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('box', django.contrib.postgres.fields.jsonb.JSONField()),
                ('script', models.CharField(blank=True, max_length=8, null=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Block')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='documentpart',
            name='segmented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='line',
            name='document_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentPart'),
        ),
        migrations.AddField(
            model_name='block',
            name='document_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentPart'),
        ),
        migrations.AddField(
            model_name='block',
            name='typology',
            field=models.ForeignKey(limit_choices_to={'target': 3}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Typology'),
        ),
    ]
