# Generated by Django 2.1.4 on 2019-03-17 15:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190304_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentprocesssettings',
            name='auto_process',
        ),
        migrations.AlterField(
            model_name='ocrmodel',
            name='file',
            field=models.FileField(upload_to='models/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mlmodel'])]),
        ),
    ]
