# Generated by Django 2.1.4 on 2018-12-12 17:30

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20181210_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentpart',
            name='segmented',
        ),
        migrations.AddField(
            model_name='documentpart',
            name='bw_backend',
            field=models.CharField(default='kraken', max_length=128),
        ),
        migrations.AddField(
            model_name='documentpart',
            name='bw_image',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.document_images_path),
        ),
        migrations.AddField(
            model_name='documentpart',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Binarizing'), (2, 'Binarized'), (3, 'Segmenting'), (4, 'Segmented'), (5, 'Transcribing')], default=0),
        ),
        migrations.AlterField(
            model_name='line',
            name='document_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.DocumentPart'),
        ),
    ]
