# Generated by Django 2.1.4 on 2019-03-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190317_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='text_direction',
            field=models.CharField(choices=[('horizontal-lr', 'Horizontal l2r'), ('horizontal-rl', 'Horizontal r2l'), ('vertical-lr', 'Vertical l2r'), ('vertical-rl', 'Vertical r2l')], default='horizontal-lr', max_length=64),
        ),
    ]
