
# Generated by Django 2.1.4 on 2018-12-17 10:58

from django.db import migrations

def initial_data(apps, schema_editor):
    TARGET_DOCUMENT = 1  # Note: not dry because get_model only get fields not consts
    TARGET_PART = 2
    Typology = apps.get_model('core', 'Typology')
    Typology.objects.create(name='Manuscript', target=TARGET_DOCUMENT)
    Typology.objects.create(name='Page', target=TARGET_PART)


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0011_auto_20181212_1730'),
    ]
    
    operations = [
        migrations.RunPython(initial_data),
    ]
