# Generated by Django 2.1.4 on 2019-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_documentpart_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpart',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Converting'), (2, 'Converted'), (3, 'Binarizing'), (4, 'Binarized'), (5, 'Segmenting'), (6, 'Segmented'), (7, 'Transcribing')], default=0),
        ),
    ]
