# Generated by Django 2.1.4 on 2018-12-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_initial_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpart',
            old_name='image',
            new_name='image_source',
        ),
    ]
