# Generated by Django 2.1.4 on 2018-12-19 10:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20181217_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineTranscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('version_source', models.CharField(default='escriptorium', editable=False, max_length=128)),
                ('version_author', models.CharField(editable=False, max_length=128)),
                ('version_created_at', models.DateTimeField(auto_now_add=True)),
                ('version_updated_at', models.DateTimeField(auto_now=True)),
                ('versions', django.contrib.postgres.fields.jsonb.JSONField(default='[]', editable=False)),
                ('text', models.CharField(max_length=2048, null=True)),
                ('graphs', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('line', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Line')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
