# Generated by Django 2.1.4 on 2019-04-17 16:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20190410_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentpart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
