# Generated by Django 2.1.4 on 2018-12-20 09:37

import django.core.files.storage
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_linetranscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OcrModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/home/robin/.config/kraken'), upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['clstm', 'pronn'])])),
                ('trained', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
        ),
        migrations.AddField(
            model_name='documentpart',
            name='transcription_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linetranscription',
            name='transcription',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.Transcription'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='transcription',
            unique_together={('name', 'document')},
        ),
    ]
