# Generated by Django 2.1.4 on 2019-04-26 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20190417_1639'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentpart',
            unique_together={('order', 'document')},
        ),
    ]
