# Generated by Django 2.1.4 on 2018-12-20 09:52

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20181220_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetranscription',
            name='versions',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list, editable=False),
        ),
    ]
