# Generated by Django 2.1.4 on 2018-12-20 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_documentprocesssettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentprocesssettings',
            old_name='automatically_process',
            new_name='auto_process',
        ),
    ]
