# Generated by Django 2.1.4 on 2019-05-02 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_document_read_direction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('name_fr', models.CharField(blank=True, max_length=128)),
                ('iso_code', models.CharField(blank=True, max_length=4)),
                ('text_direction', models.CharField(choices=[('horizontal-lr', 'Horizontal l2r'), ('horizontal-rl', 'Horizontal r2l'), ('vertical-lr', 'Vertical l2r'), ('vertical-rl', 'Vertical r2l')], default='horizontal-lr', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='main_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Script'),
        ),
    ]
