# Generated by Django 2.1.4 on 2018-12-21 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20181220_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentpart',
            old_name='image_source',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='documentpart',
            name='name',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='documentpart',
            name='typology',
            field=models.ForeignKey(blank=True, limit_choices_to={'target': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Typology'),
        ),
        migrations.AlterField(
            model_name='documentpart',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Compressed'), (2, 'Binarizing'), (3, 'Binarized'), (4, 'Segmenting'), (5, 'Segmented'), (6, 'Transcribing')], default=0),
        ),
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='binarizer',
            field=models.CharField(choices=[('kraken', 'Kraken')], default='kraken', max_length=64),
        ),
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='ocrmodel',
            field=models.ForeignKey(blank=True, limit_choices_to={'trained': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.OcrModel', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='documentprocesssettings',
            name='typology',
            field=models.ForeignKey(blank=True, limit_choices_to={'target': 2}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Typology'),
        ),
    ]
