# Generated by Django 2.1.4 on 2018-12-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20181221_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linetranscription',
            old_name='text',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='linetranscription',
            name='line',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcriptions', to='core.Line'),
        ),
        migrations.AlterField(
            model_name='transcription',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcriptions', to='core.Document'),
        ),
        migrations.AlterUniqueTogether(
            name='linetranscription',
            unique_together={('line', 'transcription')},
        ),
    ]
