# Generated by Django 2.1.4 on 2019-05-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20190507_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
