# Generated by Django 2.1.4 on 2019-05-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20190507_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentpart',
            name='original_filename',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
