# Generated by Django 2.1.4 on 2019-05-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_documentpart_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Script'),
        ),
    ]
