# Generated by Django 2.1.4 on 2019-05-21 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0025_auto_20190520_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ocrmodel',
            name='trained',
        ),
        migrations.AddField(
            model_name='ocrmodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
