# Generated by Django 2.1.4 on 2019-05-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20190521_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='training',
            field=models.BooleanField(default=False),
        ),
    ]
