# Generated by Django 2.1.4 on 2019-05-27 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_ocrmodel_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrmodel',
            options={'ordering': ('-version_updated_at',)},
        ),
    ]
