# Generated by Django 2.1.4 on 2019-05-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20190527_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='training_epoch',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
