# Generated by Django 2.1.4 on 2019-06-24 08:30

import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20190529_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='baseline',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='polygon',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ocrmodel',
            name='file',
            field=models.FileField(null=True, upload_to=core.models.models_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mlmodel'])]),
        ),
    ]
