# Generated by Django 2.1.4 on 2019-07-29 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20190624_0830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='line',
            old_name='polygon',
            new_name='mask',
        ),
    ]
