# Generated by Django 2.1.4 on 2019-10-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20190729_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='job',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Segment'), (2, 'Recognize')], default=2),
            preserve_default=False,
        ),
    ]
