# Generated by Django 2.1.4 on 2020-04-09 16:10

import core.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ocrmodel_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
