# Generated by Django 2.1.4 on 2020-05-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20200520_0724'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ocrmodel',
            options={'ordering': ('-version_updated_at',), 'permissions': (('can_train', 'Can train models'),)},
        ),
    ]
