# Generated by Django 2.1.4 on 2020-05-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20200520_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
