# Generated by Django 2.1.4 on 2020-06-10 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_transcription_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='valid_types',
            field=models.ManyToManyField(related_name='valid_in', to='core.Typology'),
        ),
        migrations.AddField(
            model_name='line',
            name='typology',
            field=models.ForeignKey(blank=True, limit_choices_to={'target': 4}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Typology'),
        ),
        migrations.AddField(
            model_name='typology',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typology',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='typology',
            name='target',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Document'), (2, 'Part (eg Page, Cover)'), (3, 'Block (eg Paragraph, Illustration)'), (4, 'Line (eg Main, Commentary)')]),
        ),
    ]
