# Generated by Django 2.1.4 on 2020-10-09 10:15

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_create_external_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='box',
            field=django.contrib.postgres.fields.jsonb.JSONField(validators=[core.models.validate_polygon, core.models.validate_3_points]),
        ),
        migrations.AlterField(
            model_name='line',
            name='baseline',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[core.models.validate_polygon, core.models.validate_2_points]),
        ),
        migrations.AlterField(
            model_name='line',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lines', to='core.Block'),
        ),
        migrations.AlterField(
            model_name='line',
            name='mask',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[core.models.validate_polygon, core.models.validate_3_points]),
        ),
    ]
