# Generated by Django 2.2.19 on 2021-03-24 10:16

import django.db.models.deletion
from django.db import migrations, models


def forward(apps, se):
    # delete any unbound model
    OcrModel = apps.get_model('core', 'OcrModel')
    OcrModel.objects.filter(document__isnull=True).delete()


def backward(apps, se):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0042_auto_20201009_1015'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='ocrmodel',
            name='document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_models', to='core.Document'),
        ),
    ]
