# Generated by Django 2.2.20 on 2021-04-27 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_auto_20210427_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2021, 4, 27, 10, 22, 51, 880783)),
            preserve_default=False,
        ),
    ]
