# Generated by Django 2.2.20 on 2021-05-10 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_data_share_doc_to_proj'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with_groups',
        ),
        migrations.RemoveField(
            model_name='document',
            name='shared_with_users',
        ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Project'),
        ),
        migrations.AlterField(
            model_name='document',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Draft'), (2, 'Published'), (3, 'Archived')], default=0),
        ),
    ]
