# Generated by Django 2.2.20 on 2021-05-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_datamigration_share_doc_to_proj'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='document',
        #     name='shared_with_groups',
        # ),
        # migrations.RemoveField(
        #     model_name='document',
        #     name='shared_with_users',
        # ),
        migrations.AlterField(
            model_name='document',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.Project'),
        ),
    ]
