# Generated by Django 2.2.23 on 2021-05-26 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
        ('core', '0048_auto_20210521_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OcrModelRight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_model_rights', to='auth.Group')),
                ('ocr_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocr_model_rights', to='core.OcrModel')),
                ('user', models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_model_rights', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='ocrmodelright',
            constraint=models.UniqueConstraint(fields=('user', 'group', 'ocr_model'), name='right_unique_target'),
        ),
        migrations.AddConstraint(
            model_name='ocrmodelright',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('group_id__isnull', False), ('user_id__isnull', True)), models.Q(('group_id__isnull', True), ('user_id__isnull', False)), _connector='OR'), name='user_xor_group'),
        ),
    ]
