# Generated by Django 2.2.23 on 2021-06-11 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_auto_20210526_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrmodel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.OcrModel'),
        ),
    ]
