# Generated by Django 2.2.24 on 2021-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_auto_20210614_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='line_offset',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baseline'), (1, 'Topline')], default=0, help_text='The position of the line relative to the polygon.'),
        ),
    ]
