# Generated by Django 2.2.24 on 2021-07-20 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_document_line_offset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='line_offset',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baseline'), (1, 'Topline'), (2, 'Centered')], default=0, help_text='The position of the line relative to the polygon.'),
        ),
    ]
