# Generated by Django 2.2.24 on 2021-08-02 17:49

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_document_line_offset'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('allowed_values', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, help_text='Comma separated list of possible value, leave it empty for free input.', null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('has_comments', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64)),
                ('marker_type', models.PositiveSmallIntegerField(choices=[(1, 'Rectangle'), (2, 'Polygon'), (3, 'Background Color'), (4, 'Text Color'), (5, 'Bold'), (6, 'Italic')], default=1)),
                ('marker_detail', models.CharField(blank=True, max_length=64, null=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Document')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AnnotationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('public', models.BooleanField(default=False)),
                ('default', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('coordinates', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=2), size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('start_offset', models.PositiveIntegerField()),
                ('end_offset', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextAnnotationComponentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TextAnnotation')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnnotationComponent')),
            ],
        ),
        migrations.AddField(
            model_name='textannotation',
            name='components',
            field=models.ManyToManyField(blank=True, through='core.TextAnnotationComponentValue', to='core.AnnotationComponent'),
        ),
        migrations.AddField(
            model_name='textannotation',
            name='end_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations_ends', to='core.Line'),
        ),
        migrations.AddField(
            model_name='textannotation',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentPart'),
        ),
        migrations.AddField(
            model_name='textannotation',
            name='start_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_starts', to='core.Line'),
        ),
        migrations.AddField(
            model_name='textannotation',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnnotationTaxonomy'),
        ),
        migrations.AddField(
            model_name='textannotation',
            name='transcription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Transcription'),
        ),
        migrations.CreateModel(
            name='ImageAnnotationComponentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ImageAnnotation')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnnotationComponent')),
            ],
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='components',
            field=models.ManyToManyField(blank=True, through='core.ImageAnnotationComponentValue', to='core.AnnotationComponent'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DocumentPart'),
        ),
        migrations.AddField(
            model_name='imageannotation',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.AnnotationTaxonomy'),
        ),
        migrations.AddField(
            model_name='annotationtaxonomy',
            name='typology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AnnotationType'),
        ),
        migrations.AddField(
            model_name='annotationcomponent',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='core.AnnotationTaxonomy'),
        ),
    ]
