# Generated by Django 2.2.24 on 2021-07-30 14:49

import core.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations
import jsonschema


schema = {'items': [{'properties': {'bbox': {'items': [{'contains': {'type': 'number'}, 'maxItems': 2, 'minItems': 2, 'type': 'array'}], 'maxItems': 2, 'minItems': 2, 'type': 'array'}, 'c': {'maxLength': 1, 'minLength': 1, 'type': 'string'}, 'confidence': {'maximum': 1, 'minimum': 0, 'type': 'number'}}, 'type': 'object'}], 'type': 'array'}

def forward(apps, se):
    LineTranscription = apps.get_model('core', 'LineTranscription')

    for line_transcription in LineTranscription.objects.all():
        try:
            jsonschema.validate(line_transcription.graphs, schema)
        except jsonschema.exceptions.ValidationError:
            line_transcription.graphs = [{"c": x[0], "bbox": [[x[1][0][0], x[1][0][1]], [x[1][2][0], x[1][2][1]]], "confidence": float(x[2])} for x in line_transcription.graphs]


def backward(apps, se):
    LineTranscription = apps.get_model('core', 'LineTranscription')
    for line_transcription in LineTranscription.objects.all():
        try:
            jsonschema.validate(line_transcription.graphs, schema)
            line_transcription.graphs = [
                (x["c"], [[x["bbox"][0][0], x["bbox"][0][1]] ,[], [x["bbox"][1][0], x["bbox"][1][1]], []], x['confidence'])
                for x in line_transcription.graphs]
        except jsonschema.exceptions.ValidationError:
            pass



class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_auto_20210720_0932'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
        migrations.AlterField(
            model_name='linetranscription',
            name='graphs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True, validators=[core.validators.JSONSchemaValidator(limit_value=schema)]),
        ),
    ]
