# Generated by Django 2.2.24 on 2021-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_ocrmodel_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='line_offset',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Baseline'), (1, 'Topline'), (2, 'Centered')], default=0, help_text='The position of the line relative to the polygon.'),
        ),
        migrations.AlterField(
            model_name='ocrmodeldocument',
            name='executed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrmodeldocument',
            name='trained_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
