# Generated by Django 2.2.24 on 2021-11-18 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20211008_1250'),
        ('core', '0056_auto_20211006_1320'),
    ]

    operations = [
    ]
