# Generated by Django 2.2.25 on 2022-01-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20210730_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_document', to='core.DocumentTag'),
        ),
    ]
