# Generated by Django 2.2.27 on 2022-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_auto_20220117_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='blank_char',
            field=models.CharField(blank=True, default=' ', max_length=1),
        ),
    ]
