# Generated by Django 2.2.28 on 2022-04-19 14:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations

import core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20220406_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linetranscription',
            name='graphs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, validators=[core.validators.JSONSchemaValidator(limit_value={'items': {'properties': {'c': {'maxLength': 1, 'minLength': 1, 'type': 'string'}, 'confidence': {'maximum': 1, 'minimum': 0, 'type': 'number'}, 'poly': {'items': {'contains': {'type': 'number'}, 'maxItems': 2, 'minItems': 2, 'type': 'array'}, 'minItems': 3, 'type': 'array'}}, 'type': 'object'}, 'type': 'array'})]),
        ),
    ]
