# Generated by Django 2.2.27 on 2022-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_auto_20220419_1414"),
    ]

    operations = [
        migrations.AddField(
            model_name="linetranscription",
            name="avg_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="avg_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentpart",
            name="max_avg_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
