# Generated by Django 2.2.27 on 2022-04-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_auto_20220608_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="linetranscription",
            name="avg_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transcription",
            name="avg_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="documentpart",
            name="max_avg_confidence",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='show_confidence_viz',
            field=models.BooleanField(default=False, help_text='If checked, enable toggling on and off colorized overlays for automatic transcription (OCR/HTR) confidences.', verbose_name='Show confidence visualizations'),
        ),
    ]
