# Generated by Django 2.2.27 on 2022-05-20 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0063_linetranscription_avg_confidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextualWitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='witnesses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mlmodel'])])),
                ('name', models.CharField(max_length=256)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
