# Generated by Django 4.0.5 on 2022-09-15 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_textualwitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpart',
            name='workflow_state',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Created'), (1, 'Converting'), (2, 'Converted'), (5, 'Segmenting'), (6, 'Segmented'), (7, 'Transcribing'), (8, 'Aligning'), (9, 'Aligned')], default=0),
        ),
        migrations.AlterField(
            model_name='textualwitness',
            name='file',
            field=models.FileField(upload_to='witnesses/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt'])]),
        ),
    ]
