# Generated by Django 4.0.10 on 2023-03-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_projecttag_project_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotationcomponent',
            options={'ordering': ['name']},
        ),
    ]
