# Generated by Django 4.0.10 on 2023-03-14 09:33

from django.db import migrations
from django.db.models import Count, Min


def forward(apps, se):
    # handles non unique component/document combo
    # just delete the duplicates it is a very rare case
    # and very few users have components at the time of the first migration run
    AnnotationComponent = apps.get_model('core', 'AnnotationComponent')

    qs = (AnnotationComponent.objects
          .values('document', 'name')
          .annotate(keep=Min('pk'), c=Count('pk'))
          .filter(c__gt=1))

    for group in qs:
        AnnotationComponent.objects.filter(
            document=group['document'], name=group['name']
        ).exclude(pk=group['keep']).delete()


def backward(apps, se):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_alter_annotationcomponent_options'),
    ]

    operations = [
        migrations.RunPython(forward, backward),
    ]
