# Generated by Django 4.0.10 on 2023-03-14 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_delete_non_unique_components'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotationcomponent',
            unique_together={('name', 'document')},
        ),
    ]
