# Generated by Django 4.0.10 on 2023-06-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_alter_annotationcomponent_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='guidelines',
            field=models.URLField(blank=True, help_text='An url explaining the principles that needs to be applied during manual segmentation/transcription.', null=True),
        ),
    ]
