# Generated by Django 4.0.10 on 2023-10-06 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_project_guidelines'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcription',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
