# Generated by Django 4.2.28 on 2026-02-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0074_instancesettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="VirtualCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("default_transcriptions", models.JSONField(blank=True, default=dict)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="virtual_collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="VirtualCollectionItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.virtualcollection",
                    ),
                ),
                (
                    "document_part",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.documentpart",
                    ),
                ),
                (
                    "transcription_layer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.transcription",
                    ),
                ),
            ],
            options={
                "unique_together": {("collection", "document_part")},
            },
        ),
        migrations.AddField(
            model_name="virtualcollection",
            name="parts",
            field=models.ManyToManyField(
                related_name="virtual_collections",
                through="core.VirtualCollectionItem",
                to="core.documentpart",
            ),
        ),
    ]
