# Generated by Django 4.2.30 on 2026-04-21 20:11

import django.core.validators
from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_virtualcollection_virtualcollectionitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrmodel',
            name='file',
            field=models.FileField(null=True, upload_to=core.models.models_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mlmodel', 'safetensors'])]),
        ),
    ]
