# Generated by Django 4.2.29 on 2026-06-26 04:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_qualify_existing_ocrmodels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Font',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(help_text='Font file in ttf, otf, woff or woff2 format.', upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['ttf', 'otf', 'woff', 'woff2'])])),
                ('size_adjust', models.FloatField(default=1.0, help_text='Size adjustment factor (1.0 = 100%) to normalize the visual size of this font.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='transcription_font',
            field=models.ForeignKey(blank=True, help_text="Font used to render this document's transcription content, overriding the project and user fonts.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.font'),
        ),
        migrations.AddField(
            model_name='project',
            name='transcription_font',
            field=models.ForeignKey(blank=True, help_text='Font used to render transcription content for documents in this project, unless overridden at the document level.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.font'),
        ),
    ]
