# Generated by Django 4.2.30 on 2026-06-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_font_document_transcription_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
