# Generated by Django 4.2.30 on 2026-07-18 16:48

import django.db.models.deletion
from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_block_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocktype',
            name='color',
            field=core.utils.ColorField(blank=True, default=core.utils.random_color, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='blocktype',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_types', to='core.document'),
        ),
        migrations.AddField(
            model_name='documentparttype',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_types', to='core.document'),
        ),
        migrations.AddField(
            model_name='linetype',
            name='color',
            field=core.utils.ColorField(blank=True, default=core.utils.random_color, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='linetype',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='line_types', to='core.document'),
        ),
        migrations.AddField(
            model_name='project',
            name='ontology_config',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
