# Generated by Django 4.2.29 on 2026-08-19 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_block_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='font',
            name='ascent_override',
            field=models.FloatField(blank=True, help_text='room above the baseline, raise it when tall glyphs get cut', null=True, verbose_name='ascent'),
        ),
        migrations.AddField(
            model_name='font',
            name='descent_override',
            field=models.FloatField(blank=True, help_text='room below the baseline, raise it when low glyphs get cut', null=True, verbose_name='descent'),
        ),
        migrations.AddField(
            model_name='font',
            name='input_height',
            field=models.FloatField(blank=True, help_text='in em, empty uses 1.1', null=True, verbose_name='height'),
        ),
        migrations.AddField(
            model_name='font',
            name='input_margin_bottom',
            field=models.FloatField(blank=True, help_text='in em, can be negative to take back the top padding', null=True, verbose_name='bottom margin'),
        ),
        migrations.AddField(
            model_name='font',
            name='input_margin_top',
            field=models.FloatField(blank=True, help_text='in em, moves the box down', null=True, verbose_name='top margin'),
        ),
        migrations.AddField(
            model_name='font',
            name='input_padding_bottom',
            field=models.FloatField(blank=True, help_text='in em, moves the text up', null=True, verbose_name='bottom padding'),
        ),
        migrations.AddField(
            model_name='font',
            name='input_padding_top',
            field=models.FloatField(blank=True, help_text='in em, moves the text down', null=True, verbose_name='top padding'),
        ),
        migrations.AddField(
            model_name='font',
            name='input_vertical_align',
            field=models.CharField(blank=True, choices=[('baseline', 'baseline'), ('middle', 'middle'), ('top', 'top'), ('bottom', 'bottom'), ('text-top', 'text top'), ('text-bottom', 'text bottom'), ('sub', 'subscript'), ('super', 'superscript')], default='', help_text='empty keeps the default', max_length=16, verbose_name='vertical align'),
        ),
        migrations.AddField(
            model_name='font',
            name='line_height',
            field=models.FloatField(blank=True, help_text='in em, empty keeps the default', null=True, verbose_name='line height'),
        ),
        migrations.AlterField(
            model_name='font',
            name='file',
            field=models.FileField(help_text='ttf, otf, woff or woff2', upload_to='fonts/', validators=[django.core.validators.FileExtensionValidator(['ttf', 'otf', 'woff', 'woff2'])]),
        ),
        migrations.AlterField(
            model_name='font',
            name='size_adjust',
            field=models.FloatField(default=1.0, help_text='scale factor, 1.0 keeps the font as it is', verbose_name='size'),
        ),
    ]
