# Generated by Django 4.2.30 on 2026-07-18 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_migrate_types_to_documents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='valid_block_types',
        ),
        migrations.RemoveField(
            model_name='document',
            name='valid_line_types',
        ),
        migrations.RemoveField(
            model_name='document',
            name='valid_part_types',
        ),
    ]
