# Generated by Django 4.2.30 on 2026-07-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_drop_valid_type_m2m'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='annotationtype',
            constraint=models.UniqueConstraint(fields=('name',), name='unique_annotationtype_name'),
        ),
        migrations.AddConstraint(
            model_name='blocktype',
            constraint=models.UniqueConstraint(fields=('document', 'name'), name='unique_blocktype_name_per_doc'),
        ),
        migrations.AddConstraint(
            model_name='blocktype',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True)), fields=('name',), name='unique_blocktype_template_name'),
        ),
        migrations.AddConstraint(
            model_name='documentparttype',
            constraint=models.UniqueConstraint(fields=('document', 'name'), name='unique_parttype_name_per_doc'),
        ),
        migrations.AddConstraint(
            model_name='documentparttype',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True)), fields=('name',), name='unique_parttype_template_name'),
        ),
        migrations.AddConstraint(
            model_name='linetype',
            constraint=models.UniqueConstraint(fields=('document', 'name'), name='unique_linetype_name_per_doc'),
        ),
        migrations.AddConstraint(
            model_name='linetype',
            constraint=models.UniqueConstraint(condition=models.Q(('document__isnull', True)), fields=('name',), name='unique_linetype_template_name'),
        ),
    ]
